# -*- coding: utf-8 -*-
"""PubChem_API.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NbqBO4LYTJONIi-aR9O3JROm9LMugnPO
"""

!pip install pubchempy
!pip install pubchemprops

import pubchempy as pcp
from pubchemprops.pubchemprops import *
import numpy as np
import pandas as pd
import os, sys
import time

def progress(count, total, status=''):
    bar_len = 40
    filled_len = int(round(bar_len * count / float(total)))
    percents = round(100.0 * count / float(total), 1)
    bar = '=' * filled_len + '-' * (bar_len - filled_len)
    sys.stdout.write('[%s] %s%s ...%s\r' % (bar, percents, '%', status))
    sys.stdout.flush()

c = pcp.Compound.from_cid(5090)

c.to_dict(properties=['atoms', 'bonds', 'inchi'])

c_props = get_second_layer_props(c.iupac_name, ['MolecularWeight', 'IUPAC Name', 'Canonical SMILES', 'Boiling Point', 'Vapor Pressure', 'LogP'])

filename = '/content/interactions - interactions.tsv'
def load_raw_data(filename):
    L_dataset = np.asarray(pd.read_csv(filename, delimiter='\t', usecols=range(12,14), header=(0), encoding='utf-8'))
    print(L_dataset.shape, L_dataset[0,:])
    return L_dataset

def get_smiles():
    isomeric_smiles = []
    t = 0
    for ligand in L_dataset:
        s = time.time()
        c = pcp.Compound.from_cid(ligand[1])
        smiles = c.isomeric_smiles
        isomeric_smiles.append(smiles)
        t += 1
        progress(t, L_dataset.shape[0], status=('predicting ' + str(t)))
    return isomeric_smiles

data = load_raw_data(filename)

smiles = get_smiles()